apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "clusters.extension.tkircsi.info"
spec:
  group: "extension.tkircsi.info"
  versions:
    - name: "v1alpha1"
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: "integer"
                  minimum: 1
                clusterName:
                  type: "string"
              required: ["replicas", "clusterName"]
  scope: "Namespaced"
  names:
    plural: "clusters"
    singular: "cluster"
    kind: "Cluster"
    shortNames:
    - cl
  
    